USE [master]
GO

/****** Object:  Database [185sm]    Script Date: 17.11.2021 13:02:39 ******/
CREATE DATABASE [185sm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'185sm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\185sm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'185sm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\185sm_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [185sm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [185sm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [185sm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [185sm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [185sm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [185sm] SET ARITHABORT OFF 
GO

ALTER DATABASE [185sm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [185sm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [185sm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [185sm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [185sm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [185sm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [185sm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [185sm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [185sm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [185sm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [185sm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [185sm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [185sm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [185sm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [185sm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [185sm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [185sm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [185sm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [185sm] SET  MULTI_USER 
GO

ALTER DATABASE [185sm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [185sm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [185sm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [185sm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [185sm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [185sm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [185sm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [185sm] SET  READ_WRITE 
GO

